import { describe, it, expect } from 'vitest';
import { extractAndParseCitations } from '../index.js';
import type { AiSourceComponents } from '@legalcitation/shared';

describe('AI source citation detection and parsing', () => {
  it('parses an LLM prompt citation', () => {
    const results = extractAndParseCitations(
      'Luke Cronin, Google Gemini Advanced, "Who would make a better Supreme Court Justice: Beyoncé or Taylor Swift?" (Mar. 29, 2024) (on file with the Columbia Law Review).'
    );
    const aiResults = results.filter(r => r.type === 'ai_source');
    expect(aiResults.length).toBeGreaterThanOrEqual(1);
    const comp = aiResults[0].components as AiSourceComponents;
    expect(comp.modelName).toContain('Gemini');
    expect(comp.subtype).toBe('llm');
    expect(comp.onFileWith).toBeTruthy();
  });

  it('parses a search result citation', () => {
    const results = extractAndParseCitations(
      'Bing, "The Bluebook", 6,050,000 results (May 22, 2024) (on file with the Harvard Law Review).'
    );
    const aiResults = results.filter(r => r.type === 'ai_source');
    expect(aiResults.length).toBeGreaterThanOrEqual(1);
    const comp = aiResults[0].components as AiSourceComponents;
    expect(comp.subtype).toBe('search');
    expect(comp.searchEngine).toContain('Bing');
  });

  it('parses a generated content citation', () => {
    const results = extractAndParseCitations(
      'Illustration of a Tornado on the Moon (on file with the Columbia Law Review) (generated by DALL-E 3).'
    );
    const aiResults = results.filter(r => r.type === 'ai_source');
    expect(aiResults.length).toBeGreaterThanOrEqual(1);
    const comp = aiResults[0].components as AiSourceComponents;
    expect(comp.subtype).toBe('generated_content');
    expect(comp.generatedByModel).toContain('DALL-E');
  });

  it('detects ChatGPT citations', () => {
    const results = extractAndParseCitations(
      'Author, ChatGPT, "Explain the doctrine of stare decisis" (Jan. 15, 2025) (on file with author).'
    );
    const aiResults = results.filter(r => r.type === 'ai_source');
    expect(aiResults.length).toBeGreaterThanOrEqual(1);
    const comp = aiResults[0].components as AiSourceComponents;
    expect(comp.modelName).toContain('ChatGPT');
  });
});
