/**
 * Bluebook Table T6 — Case Names and Institutional Authors in Citations
 * Maps full words to their Bluebook abbreviations.
 * Plurals are formed by adding "s" unless otherwise noted.
 */
export const T6_ABBREVIATIONS: Record<string, string> = {
  'Academic': 'Acad.',
  'Academy': 'Acad.',
  'Accountant': 'Acct.',
  'Accounting': 'Acct.',
  'Accountancy': 'Acct.',
  'Administrative': 'Admin.',
  'Administration': 'Admin.',
  'Administrator': "Adm'r",
  'Administratrix': "Adm'x",
  'Advertising': 'Advert.',
  'Advocate': 'Advoc.',
  'Advocacy': 'Advoc.',
  'Affair': 'Aff.',
  'Affairs': 'Affs.',
  'African': 'Afr.',
  'Africa': 'Afr.',
  'Agricultural': 'Agric.',
  'Agriculture': 'Agric.',
  'Alliance': 'All.',
  'Alternative': 'Alt.',
  'Amendment': 'Amend.',
  'American': 'Am.',
  'America': 'Am.',
  'Ancestry': 'Anc.',
  'and': '&',
  'Annual': 'Ann.',
  'Appellate': 'App.',
  'Arbitration': 'Arb.',
  'Arbitrator': 'Arb.',
  'Artificial Intelligence': 'A.I.',
  'Associate': 'Assoc.',
  'Association': "Ass'n",
  'Atlantic': 'Atl.',
  'Attorney': "Att'y",
  'Authority': 'Auth.',
  'Automobile': 'Auto.',
  'Automotive': 'Auto.',
  'Avenue': 'Ave.',
  'Bankruptcy': 'Bankr.',
  'Behavioral': 'Behav.',
  'Behavior': 'Behav.',
  'Board': 'Bd.',
  'British': 'Brit.',
  'Broadcaster': 'Broad.',
  'Broadcasting': 'Broad.',
  'Brothers': 'Bros.',
  'Brotherhood': 'Bhd.',
  'Building': 'Bldg.',
  'Bulletin': 'Bull.',
  'Business': 'Bus.',
  'Businesses': 'Bus.',
  'Capital': 'Cap.',
  'Casualty': 'Cas.',
  'Casualties': 'Cas.',
  'Catholic': 'Cath.',
  'Center': 'Ctr.',
  'Centre': 'Ctr.',
  'Central': 'Cent.',
  'Chemical': 'Chem.',
  'Children': 'Child.',
  'Chronicle': 'Chron.',
  'Circuit': 'Cir.',
  'Civil': 'Civ.',
  'Civil Liberties': 'C.L.',
  'Civil Liberty': 'C.L.',
  'Civil Rights': 'C.R.',
  'Coalition': 'Coal.',
  'College': 'Coll.',
  'Commentary': 'Comment.',
  'Commerce': 'Com.',
  'Commercial': 'Com.',
  'Commission': "Comm'n",
  'Commissioner': "Comm'r",
  'Committee': 'Comm.',
  'Communication': "Commc'n",
  'Community': 'Cmty.',
  'Company': 'Co.',
  'Comparative': 'Compar.',
  'Compensation': 'Comp.',
  'Computer': 'Comput.',
  'Condominium': 'Condo.',
  'Conference': 'Conf.',
  'Congressional': 'Cong.',
  'Congress': 'Cong.',
  'Consolidated': 'Consol.',
  'Constitutional': 'Const.',
  'Constitution': 'Const.',
  'Construction': 'Constr.',
  'Contemporary': 'Contemp.',
  'Continental': "Cont'l",
  'Contract': 'Cont.',
  'Conveyance': 'Conv.',
  'Conveyancer': 'Conv.',
  'Cooperation': 'Coop.',
  'Cooperative': 'Coop.',
  'Corporate': 'Corp.',
  'Corporation': 'Corp.',
  'Correctional': 'Corr.',
  'Corrections': 'Corr.',
  'Correction': 'Corr.',
  'Cosmetic': 'Cosm.',
  'Counselor': 'Couns.',
  'Counselors': 'Couns.',
  "Counselor's": "Couns.",
  'County': 'Cnty.',
  'Court': 'Ct.',
  'Criminal': 'Crim.',
  'Defendant': 'Def.',
  'Defender': 'Def.',
  'Defense': 'Def.',
  'Delinquent': 'Delinq.',
  'Delinquency': 'Delinq.',
  'Department': "Dep't",
  'Detention': 'Det.',
  'Developer': 'Dev.',
  'Development': 'Dev.',
  'Digest': 'Dig.',
  'Digital': 'Digit.',
  'Diplomacy': 'Dipl.',
  'Director': 'Dir.',
  'Discount': 'Disc.',
  'Dispute': 'Disp.',
  'Distributor': 'Distrib.',
  'Distributing': 'Distrib.',
  'Distribution': 'Distrib.',
  'District': 'Dist.',
  'Division': 'Div.',
  'Doctor': 'Dr.',
  'Eastern': 'E.',
  'East': 'E.',
  'Economic': 'Econ.',
  'Economical': 'Econ.',
  'Economics': 'Econ.',
  'Economy': 'Econ.',
  'Editorial': 'Ed.',
  'Editor': 'Ed.',
  'Educational': 'Educ.',
  'Education': 'Educ.',
  'Electric': 'Elec.',
  'Electrical': 'Elec.',
  'Electricity': 'Elec.',
  'Electronic': 'Elec.',
  'Employee': 'Emp.',
  'Employer': 'Emp.',
  'Employment': 'Emp.',
  'Enforcement': "Enf't",
  'Engineer': "Eng'r",
  'Engineering': "Eng'g",
  'English': 'Eng.',
  'Enterprise': 'Enter.',
  'Entertainment': 'Ent.',
  'Environmental': "Env't",
  'Environment': "Env't",
  'Equality': 'Equal.',
  'Equipment': 'Equip.',
  'Estate': 'Est.',
  'European': 'Eur.',
  'Europe': 'Eur.',
  'Examiner': "Exam'r",
  'Exchange': 'Exch.',
  'Executive': 'Exec.',
  'Executor': "Ex'r",
  'Executrix': "Ex'x",
  'Exploration': 'Expl.',
  'Exploratory': 'Expl.',
  'Exporter': 'Exp.',
  'Exportation': 'Exp.',
  'Export': 'Exp.',
  'Faculty': 'Fac.',
  'Family': 'Fam.',
  'Federal': 'Fed.',
  'Federation': "Fed'n",
  'Fidelity': 'Fid.',
  'Finance': 'Fin.',
  'Financial': 'Fin.',
  'Financing': 'Fin.',
  'Fortnightly': 'Fort.',
  'Forum': 'F.',
  'Foundation': 'Found.',
  'General': 'Gen.',
  'Global': 'Glob.',
  'Government': "Gov't",
  'Group': 'Grp.',
  'Guaranty': 'Guar.',
  'Guarantor': 'Guar.',
  'Hispanic': 'Hisp.',
  'Historical': 'Hist.',
  'History': 'Hist.',
  'Hospital': 'Hosp.',
  'Hospitality': 'Hosp.',
  'Housing': 'Hous.',
  'Human': 'Hum.',
  'Humanity': 'Human.',
  'Immigration': 'Immigr.',
  'Importer': 'Imp.',
  'Importation': 'Imp.',
  'Import': 'Imp.',
  'Incorporated': 'Inc.',
  'Indemnity': 'Indem.',
  'Independence': 'Indep.',
  'Independent': 'Indep.',
  'Industrial': 'Indus.',
  'Industry': 'Indus.',
  'Industries': 'Indus.',
  'Inequality': 'Ineq.',
  'Information': 'Info.',
  'Injury': 'Inj.',
  'Institute': 'Inst.',
  'Institution': 'Inst.',
  'Insurance': 'Ins.',
  'Intellectual': 'Intell.',
  'Intelligence': 'Intel.',
  'Interdisciplinary': 'Interdisc.',
  'Interest': 'Int.',
  'International': "Int'l",
  'Investment': 'Inv.',
  'Investor': 'Inv.',
  'Journal': 'J.',
  'Journals': 'J.',
  'Judicial': 'Jud.',
  'Juridical': 'Jurid.',
  'Jurisprudence': 'Juris.',
  'Justice': 'Just.',
  'Juvenile': 'Juv.',
  'Labor': 'Lab.',
  'Laboratory': "Lab'y",
  'Law': 'L.',
  'Laws': 'L.',
  'Lawyer': 'Law.',
  'Legislation': 'Legis.',
  'Legislative': 'Legis.',
  'Liability': 'Liab.',
  'Library': 'Libr.',
  'Librarian': 'Libr.',
  'Limited': 'Ltd.',
  'Litigation': 'Litig.',
  'Local': 'Loc.',
  'Machinery': 'Mach.',
  'Machine': 'Mach.',
  'Magazine': 'Mag.',
  'Maintenance': 'Maint.',
  'Management': 'Mgmt.',
  'Manufacturer': 'Mfr.',
  'Manufacturing': 'Mfg.',
  'Maritime': 'Mar.',
  'Market': 'Mkt.',
  'Marketing': 'Mktg.',
  'Matrimonial': 'Matrim.',
  'Mechanical': 'Mech.',
  'Mechanic': 'Mech.',
  'Medical': 'Med.',
  'Medicinal': 'Med.',
  'Medicine': 'Med.',
  'Memorial': "Mem'l",
  'Merchant': 'Merch.',
  'Merchandise': 'Merch.',
  'Merchandising': 'Merch.',
  'Metropolitan': 'Metro.',
  'Military': 'Mil.',
  'Mineral': 'Min.',
  'Modern': 'Mod.',
  'Mortgage': 'Mortg.',
  'Municipal': 'Mun.',
  'Municipality': 'Mun.',
  'Mutual': 'Mut.',
  'National': "Nat'l",
  'Nationality': "Nat'y",
  'Natural': 'Nat.',
  'Negligence': 'Negl.',
  'Negotiation': 'Negot.',
  'Negotiator': 'Negot.',
  'Newsletter': 'Newsl.',
  'Northern': 'N.',
  'North': 'N.',
  'Northeastern': 'Ne.',
  'Northeast': 'Ne.',
  'Northwestern': 'Nw.',
  'Northwest': 'Nw.',
  'Number': 'No.',
  'Office': 'Off.',
  'Official': 'Off.',
  'Opinion': 'Op.',
  'Order': 'Ord.',
  'Organization': 'Org.',
  'Organizing': 'Org.',
  'Pacific': 'Pac.',
  'Parish': 'Par.',
  'Partnership': "P'ship",
  'Patent': 'Pat.',
  'Personal': 'Pers.',
  'Personnel': 'Pers.',
  'Person': 'Pers.',
  'Perspective': 'Persp.',
  'Pharmaceutical': 'Pharm.',
  'Philosophical': 'Phil.',
  'Philosophy': 'Phil.',
  'Planning': 'Plan.',
  'Policy': "Pol'y",
  'Political': 'Pol.',
  'Politics': 'Pol.',
  'Practical': 'Prac.',
  'Practice': 'Prac.',
  'Practitioner': 'Prac.',
  'Preservation': 'Pres.',
  'Preserve': 'Pres.',
  'Privacy': 'Priv.',
  'Private': 'Priv.',
  'Probate': 'Prob.',
  'Probation': 'Prob.',
  'Problems': 'Probs.',
  'Proceedings': 'Proc.',
  'Procedure': 'Proc.',
  'Production': 'Prod.',
  'Product': 'Prod.',
  'Professional': 'Pro.',
  'Property': 'Prop.',
  'Protection': 'Prot.',
  'Psychological': 'Psych.',
  'Psychologist': 'Psych.',
  'Psychology': 'Psych.',
  'Public': 'Pub.',
  'Publication': "Publ'n",
  'Publishing': "Publ'g",
  'Quarterly': 'Q.',
  'Railroad': 'R.R.',
  'Railway': 'Ry.',
  'Record': 'Rec.',
  'Referee': 'Ref.',
  'Refining': 'Refin.',
  'Refinement': 'Refin.',
  'Regional': "Reg'l",
  'Register': 'Reg.',
  'Regulation': 'Regul.',
  'Regulator': 'Regul.',
  'Regulatory': 'Regul.',
  'Rehabilitation': 'Rehab.',
  'Rehabilitative': 'Rehab.',
  'Relation': 'Rel.',
  'Reporter': 'Rep.',
  'Report': 'Rep.',
  'Reproduction': 'Reprod.',
  'Reproductive': 'Reprod.',
  'Research': 'Rsch.',
  'Reservation': 'Rsrv.',
  'Reserve': 'Rsrv.',
  'Resolution': 'Resol.',
  'Resource': 'Res.',
  'Resources': 'Res.',
  'Responsibility': 'Resp.',
  'Restaurant': 'Rest.',
  'Retirement': 'Ret.',
  'Review': 'Rev.',
  'Revista': 'Rev.',
  'Rights': 'Rts.',
  'Road': 'Rd.',
  'Savings': 'Sav.',
  'School': 'Sch.',
  'Science': 'Sci.',
  'Scientific': 'Sci.',
  'Scottish': 'Scot.',
  'Secretary': "Sec'y",
  'Security': 'Sec.',
  'Securities': 'Sec.',
  'Sentencing': "Sent'g",
  'Service': 'Serv.',
  'Shareholder': "S'holder",
  'Stockholder': "S'holder",
  'Social': 'Soc.',
  'Society': "Soc'y",
  'Sociological': 'Socio.',
  'Sociology': 'Socio.',
  'Solicitor': 'Solic.',
  'Solution': 'Sol.',
  'Southern': 'S.',
  'South': 'S.',
  'Southeastern': 'Se.',
  'Southeast': 'Se.',
  'Southwestern': 'Sw.',
  'Southwest': 'Sw.',
  'Statistics': 'Stat.',
  'Statistical': 'Stat.',
  'Steamship': 'S.S.',
  'Steamships': 'S.S.',
  'Street': 'St.',
  'Studies': 'Stud.',
  'Subcommittee': 'Subcomm.',
  'Supreme Court': 'Sup. Ct.',
  'Surety': 'Sur.',
  'Survey': 'Surv.',
  'Symposium': 'Symp.',
  'System': 'Sys.',
  'Systems': 'Sys.',
  'Taxation': "Tax'n",
  'Teacher': 'Tchr.',
  'Technical': 'Tech.',
  'Technique': 'Tech.',
  'Technology': 'Tech.',
  'Technological': 'Tech.',
  'Telecommunication': 'Telecomm.',
  'Telephone': 'Tel.',
  'Telegraph': 'Tel.',
  'Temporary': 'Temp.',
  'Township': 'Twp.',
  'Transcontinental': 'Transcon.',
  'Transnational': "Transnat'l",
  'Transportation': 'Transp.',
  'Transport': 'Transp.',
  'Tribune': 'Trib.',
  'Trust': 'Tr.',
  'Trustee': 'Tr.',
  'Turnpike': 'Tpk.',
  'Uniform': 'Unif.',
  'United States': 'U.S.',
  'University': 'Univ.',
  'Urban': 'Urb.',
  'Utility': 'Util.',
  'Village': 'Vill.',
  'Week': 'Wk.',
  'Weekly': 'Wkly.',
  'Western': 'W.',
  'West': 'W.',
  'Yearbook': 'Y.B.',
  'Year Book': 'Y.B.',
};

/**
 * Words that should ONLY be abbreviated in textual sentences
 * (R. 10.2.1(c)) — the "eight words" rule
 */
export const TEXTUAL_SENTENCE_ABBREVIATIONS: Record<string, string> = {
  'and': '&',
  'Association': "Ass'n",
  'Brothers': 'Bros.',
  'Company': 'Co.',
  'Corporation': 'Corp.',
  'Incorporated': 'Inc.',
  'Limited': 'Ltd.',
  'Number': 'No.',
};

/**
 * Words indicating business firm designation that can trigger
 * omission of "Inc.", "Ltd.", etc. per R. 10.2.1(h)
 */
export const BUSINESS_FIRM_INDICATORS = [
  "Ass'n", 'Bros.', 'Co.', 'Corp.', 'Ins.', 'R.R.',
];

/**
 * Descriptive terms to omit from party names per R. 10.2.1(e)
 */
export const OMIT_DESCRIPTIVE_TERMS = [
  'Administrator', 'Administratrix', 'Appellee', 'Appellant',
  'Executor', 'Executrix', 'Licensee', 'Trustee',
  'Plaintiff', 'Defendant', 'Petitioner', 'Respondent',
];

/**
 * Procedural phrases mapping per R. 10.2.1(b)
 */
export const PROCEDURAL_PHRASES: Record<string, string> = {
  'In the Matter of': 'In re',
  'in the matter of': 'In re',
  'In The Matter Of': 'In re',
  'Petition of': 'In re',
  'petition of': 'In re',
  'Application of': 'In re',
  'application of': 'In re',
  'on the relation of': 'ex rel.',
  'On the Relation of': 'ex rel.',
  'on behalf of': 'ex rel.',
  'On Behalf of': 'ex rel.',
  'as next friend of': 'ex rel.',
  'for the use of': 'ex rel.',
};
