/**
 * BT1 — Court Document Abbreviations
 * Suggested abbreviations for words commonly found in titles of court documents.
 * Use these abbreviations in citations per Bluepages B17.
 *
 * Words where abbreviation equals the full word are NOT abbreviated.
 */
export const BT1_COURT_DOCUMENTS: Record<string, string> = {
  'Admission': 'Admis.',
  'Affidavit': 'Aff.',
  'Affirm': 'Affirm',
  'Amended': 'Am.',
  'Answer': 'Answer',
  'Appeal': 'Appeal',
  'Appellant': 'Appellant',
  'Appellee': 'Appellee',
  'Appendix': 'App.',
  'Application': 'Appl.',
  'Argument': 'Arg.',
  'Attachment': 'Attach.',
  'Attorney': "Att'y",
  'Brief': 'Br.',
  'Certiorari': 'Cert.',
  'Compel': 'Compel',
  'Complaint': 'Compl.',
  'Counterclaim': 'Countercl.',
  'Court': 'Ct.',
  'Cross-claim': 'Cross-cl.',
  'Declaration': 'Decl.',
  'Defendant': 'Def.',
  "Defendant's": "Def.'s",
  'Defendants': 'Defs.',
  "Defendants'": "Defs.'",
  'Demurrer': 'Dem.',
  'Deny': 'Den.',
  'Denying': 'Den.',
  'Deposition': 'Dep.',
  'Discovery': 'Disc.',
  'Dismiss': 'Dismiss',
  'Docket': 'Dkt.',
  'Document': 'Doc.',
  'Evidence': 'Evid.',
  'Exhibit': 'Ex.',
  'Grant': 'Grant',
  'Hearing': "Hr'g",
  'Injunction': 'Inj.',
  'Instruction': 'Instr.',
  'Interrogatory': 'Interrog.',
  'Joint Appendix': 'J.A.',
  'Judgment': 'J.',
  'Limine': 'Lim.',
  'Memorandum': 'Mem.',
  'Minute': 'Min.',
  'Motion': 'Mot.',
  'Objection': 'Obj.',
  'Opinion': 'Op.',
  'Opposition': "Opp'n",
  'Order': 'Order',
  'Order to Show Cause': 'O.S.C.',
  'Petition': 'Pet.',
  'Petitioner': "Pet'r",
  "Petitioner's": "Pet'r's",
  'Petitioners': "Pet'rs",
  "Petitioners'": "Pet'rs'",
  'Plaintiff': 'Pl.',
  "Plaintiff's": "Pl.'s",
  'Plaintiffs': 'Pls.',
  "Plaintiffs'": "Pls.'",
  'Points and Authorities': 'P. & A.',
  'Preliminary': 'Prelim.',
  'Produce': 'Produc.',
  'Production': 'Produc.',
  'Quash': 'Quash',
  'Reconsideration': 'Recons.',
  'Record': 'R.',
  'Rehearing': "Reh'g",
  'Reply': 'Reply',
  'Report and Recommendation': 'R. & R.',
  'Reporter': 'Rep.',
  'Request': 'Req.',
  'Respondent': "Resp't",
  'Response': 'Resp.',
  'Stay': 'Stay',
  'Subpoena': 'Subpoena',
  'Summary': 'Summ.',
  'Supplement': 'Suppl.',
  'Supplemental': 'Suppl.',
  'Support': 'Supp.',
  'Suppress': 'Suppress',
  'Temporary Restraining Order': 'TRO',
  'Testimony': 'Test.',
  'Transcript': 'Tr.',
  'Verified Statement': 'V.S.',
};

/** Words that are NOT abbreviated in BT1 (abbreviation = full word) */
export const BT1_NOT_ABBREVIATED = new Set([
  'Affirm', 'Answer', 'Appeal', 'Appellant', 'Appellee',
  'Compel', 'Dismiss', 'Grant', 'Order', 'Quash',
  'Reply', 'Stay', 'Subpoena', 'Suppress',
]);
