/**
 * T13 — Institutional Names in Periodical Titles
 * Common institutional names found in periodical titles.
 *
 * KEY RULES:
 * - Abbreviate "University" as "U."
 * - Omit "a," "at," "in," "of," and "the" (but retain "on")
 * - If title is one word after omitting articles, do NOT abbreviate
 * - Omit commas from periodical title abbreviations
 * - For titles with colons, omit words after colon
 * - For online supplements, append supplement name
 */
export const T13_PERIODICALS: Record<string, string> = {
  'Air Force': 'A.F.',
  'Albany': 'Alb.',
  'American Intellectual Property Law Association': 'AIPLA',
  'American Medical Association': 'AMA',
  'Journal of the American Medical Association': 'JAMA',
  'American Society of Composers, Authors & Publishers': 'ASCAP',
  'Boston College': 'B.C.',
  'Boston University': 'B.U.',
  'Brigham Young University': 'BYU',
  'Brooklyn': 'Brook.',
  'Buffalo': 'Buff.',
  'California': 'Calif.',
  'Capital': 'Cap.',
  'Chapman': 'Chap.',
  'Chartered Life Underwriters': 'C.L.U.',
  'Cincinnati': 'Cin.',
  'City University of New York': 'CUNY',
  'Cleveland': 'Clev.',
  'Columbia': 'Colum.',
  'Cornell': 'Corn.',
  'Cumberland': 'Cumb.',
  'Detroit': 'Det.',
  'Dickinson': 'Dick.',
  'Duquesne': 'Duq.',
  'Florida International University': 'FIU',
  'George Mason': 'Geo. Mason',
  'George Washington': 'Geo. Wash.',
  'Georgetown': 'Geo.',
  'Gonzaga': 'Gonz.',
  'Harvard': 'Harv.',
  'Howard': 'How.',
  'John Marshall': 'J. Marshall',
  'Judge Advocate General': 'JAG',
  'Lawyers Reports Annotated': 'L.R.A.',
  'Loyola': 'Loy.',
  'Marquette': 'Marq.',
  'Memphis': 'Mem.',
  'New England': 'New Eng.',
  'New England Journal of Medicine': 'NEJM',
  'New York University': 'N.Y.U.',
  'Penn State': 'Penn. St.',
  'Pepperdine': 'Pepp.',
  'Pittsburgh': 'Pitt.',
  'Proceedings of the National Academy of Sciences': 'PNAS',
  'Richmond': 'Rich.',
  'Saint Louis': 'St. Louis',
  'Southern Methodist University': 'SMU',
  'Stanford': 'Stan.',
  'State': 'St.',
  'Temple': 'Temp.',
  'Thomas Jefferson': 'T. Jefferson',
  'Thurgood Marshall': 'T. Marshall',
  'Toledo': 'Tol.',
  'Tulane': 'Tul.',
  'Universidad de Puerto Rico': 'U.P.R.',
  'University of California': 'U.C.',
  'University of California, Los Angeles': 'UCLA',
  'University of Missouri-Kansas City': 'UMKC',
  'University of West Los Angeles': 'UWLA',
  'Vanderbilt': 'Vand.',
  'Villanova': 'Vill.',
  'Washington & Lee': 'Wash. & Lee',
  'William & Mary': 'Wm. & Mary',
  'William Mitchell': 'Wm. Mitchell',
};

/** Words to omit from periodical titles per T13 */
export const PERIODICAL_OMIT_WORDS = new Set([
  'a', 'an', 'at', 'in', 'of', 'the', 'and', 'for', 'on', 'to', 'from', 'by',
]);

/**
 * JOURNAL_ABBREVIATIONS — Full journal name → Bluebook abbreviation.
 *
 * 200+ entries covering top law reviews, specialty journals, state bar journals,
 * and interdisciplinary/international journals per T13.
 */
export const JOURNAL_ABBREVIATIONS: Record<string, string> = {
  // ── Top Law Reviews ─────────────────────────────────────────────
  'Harvard Law Review': 'Harv. L. Rev.',
  'Yale Law Journal': 'Yale L.J.',
  'Stanford Law Review': 'Stan. L. Rev.',
  'Columbia Law Review': 'Colum. L. Rev.',
  'Michigan Law Review': 'Mich. L. Rev.',
  'University of Pennsylvania Law Review': 'U. Pa. L. Rev.',
  'California Law Review': 'Cal. L. Rev.',
  'Georgetown Law Journal': 'Geo. L.J.',
  'New York University Law Review': 'N.Y.U. L. Rev.',
  'Virginia Law Review': 'Va. L. Rev.',
  'Duke Law Journal': 'Duke L.J.',
  'Northwestern University Law Review': 'Nw. U. L. Rev.',
  'Texas Law Review': 'Tex. L. Rev.',
  'University of Chicago Law Review': 'U. Chi. L. Rev.',
  'Minnesota Law Review': 'Minn. L. Rev.',
  'Iowa Law Review': 'Iowa L. Rev.',
  'Cornell Law Review': 'Cornell L. Rev.',
  'Vanderbilt Law Review': 'Vand. L. Rev.',
  'Boston University Law Review': 'B.U. L. Rev.',
  'Notre Dame Law Review': 'Notre Dame L. Rev.',
  'University of Illinois Law Review': 'U. Ill. L. Rev.',
  'Wisconsin Law Review': 'Wis. L. Rev.',
  'Southern California Law Review': 'S. Cal. L. Rev.',
  'UCLA Law Review': 'UCLA L. Rev.',
  'George Washington Law Review': 'Geo. Wash. L. Rev.',
  'Fordham Law Review': 'Fordham L. Rev.',
  'Washington Law Review': 'Wash. L. Rev.',
  'Ohio State Law Journal': 'Ohio St. L.J.',
  'Emory Law Journal': 'Emory L.J.',
  'William and Mary Law Review': 'Wm. & Mary L. Rev.',
  'Hastings Law Journal': 'Hastings L.J.',
  'Indiana Law Journal': 'Ind. L.J.',
  'Rutgers Law Review': 'Rutgers L. Rev.',
  'North Carolina Law Review': 'N.C. L. Rev.',
  'Washington University Law Review': 'Wash. U. L. Rev.',
  'Boston College Law Review': 'B.C. L. Rev.',
  'Georgia Law Review': 'Ga. L. Rev.',
  'Florida Law Review': 'Fla. L. Rev.',
  'Tulane Law Review': 'Tul. L. Rev.',
  'Arizona State Law Journal': 'Ariz. St. L.J.',
  'Brigham Young University Law Review': 'BYU L. Rev.',
  'Wake Forest Law Review': 'Wake Forest L. Rev.',
  'Colorado Law Review': 'Colo. L. Rev.',
  'Connecticut Law Review': 'Conn. L. Rev.',
  'Temple Law Review': 'Temp. L. Rev.',
  'Cardozo Law Review': 'Cardozo L. Rev.',
  'Chicago-Kent Law Review': 'Chi.-Kent L. Rev.',
  'Michigan State Law Review': 'Mich. St. L. Rev.',

  // ── Specialty Journals ──────────────────────────────────────────
  'American Criminal Law Review': 'Am. Crim. L. Rev.',
  'Antitrust Law Journal': 'Antitrust L.J.',
  'Berkeley Technology Law Journal': 'Berkeley Tech. L.J.',
  'Cardozo Arts and Entertainment Law Journal': 'Cardozo Arts & Ent. L.J.',
  'Columbia Business Law Review': 'Colum. Bus. L. Rev.',
  'Columbia Human Rights Law Review': 'Colum. Hum. Rts. L. Rev.',
  'Columbia Journal of Environmental Law': 'Colum. J. Env\'t L.',
  'Columbia Journal of Gender and Law': 'Colum. J. Gender & L.',
  'Columbia Journal of Law and Social Problems': 'Colum. J.L. & Soc. Probs.',
  'Columbia Journal of Transnational Law': 'Colum. J. Transnat\'l L.',
  'Cornell International Law Journal': 'Cornell Int\'l L.J.',
  'DePaul Law Review': 'DePaul L. Rev.',
  'Ecology Law Quarterly': 'Ecology L.Q.',
  'Environmental Law': 'Env\'t L.',
  'Environmental Law Reporter': 'Env\'t L. Rep.',
  'Family Law Quarterly': 'Fam. L.Q.',
  'Federal Communications Law Journal': 'Fed. Commc\'n L.J.',
  'Food and Drug Law Journal': 'Food & Drug L.J.',
  'Georgetown Immigration Law Journal': 'Geo. Immigr. L.J.',
  'Georgetown Journal of Legal Ethics': 'Geo. J. Legal Ethics',
  'Harvard Civil Rights-Civil Liberties Law Review': 'Harv. C.R.-C.L. L. Rev.',
  'Harvard Environmental Law Review': 'Harv. Env\'t L. Rev.',
  'Harvard Human Rights Journal': 'Harv. Hum. Rts. J.',
  'Harvard International Law Journal': 'Harv. Int\'l L.J.',
  'Harvard Journal of Law and Public Policy': 'Harv. J.L. & Pub. Pol\'y',
  'Harvard Journal of Law and Technology': 'Harv. J.L. & Tech.',
  'Harvard Journal on Legislation': 'Harv. J. on Legis.',
  'Harvard Law and Policy Review': 'Harv. L. & Pol\'y Rev.',
  'Hastings Constitutional Law Quarterly': 'Hastings Const. L.Q.',
  'Health Matrix': 'Health Matrix',
  'Houston Law Review': 'Hous. L. Rev.',
  'Howard Law Journal': 'How. L.J.',
  'Indiana Law Review': 'Ind. L. Rev.',
  'Intellectual Property Law Review': 'Intell. Prop. L. Rev.',
  'Journal of Air Law and Commerce': 'J. Air L. & Com.',
  'Journal of Corporation Law': 'J. Corp. L.',
  'Journal of Criminal Law and Criminology': 'J. Crim. L. & Criminology',
  'Journal of Environmental Law and Litigation': 'J. Env\'t L. & Litig.',
  'Journal of Gender, Race and Justice': 'J. Gender Race & Just.',
  'Journal of Health Law': 'J. Health L.',
  'Journal of Intellectual Property Law': 'J. Intell. Prop. L.',
  'Journal of International Law': 'J. Int\'l L.',
  'Journal of Land Use and Environmental Law': 'J. Land Use & Env\'t L.',
  'Journal of Law and Commerce': 'J.L. & Com.',
  'Journal of Law and Economics': 'J.L. & Econ.',
  'Journal of Law and Education': 'J.L. & Educ.',
  'Journal of Law and Health': 'J.L. & Health',
  'Journal of Law and Policy': 'J.L. & Pol\'y',
  'Journal of Law and Politics': 'J.L. & Pol.',
  'Journal of Law and Social Policy': 'J.L. & Soc. Pol\'y',
  'Journal of Law, Medicine and Ethics': 'J.L. Med. & Ethics',
  'Journal of Legal Education': 'J. Legal Educ.',
  'Journal of Legal Studies': 'J. Legal Stud.',
  'Journal of Maritime Law and Commerce': 'J. Mar. L. & Com.',
  'Journal of Technology Law and Policy': 'J. Tech. L. & Pol\'y',
  'Kentucky Law Journal': 'Ky. L.J.',
  'Labor Law Journal': 'Lab. L.J.',
  'Law and Contemporary Problems': 'Law & Contemp. Probs.',
  'Law and Social Inquiry': 'Law & Soc. Inquiry',
  'Loyola Law Review': 'Loy. L. Rev.',
  'Loyola of Los Angeles Law Review': 'Loy. L.A. L. Rev.',
  'Loyola University Chicago Law Journal': 'Loy. U. Chi. L.J.',
  'Marquette Law Review': 'Marq. L. Rev.',
  'Maryland Law Review': 'Md. L. Rev.',
  'Mercer Law Review': 'Mercer L. Rev.',
  'Military Law Review': 'Mil. L. Rev.',
  'Mississippi Law Journal': 'Miss. L.J.',
  'Missouri Law Review': 'Mo. L. Rev.',
  'Montana Law Review': 'Mont. L. Rev.',
  'Natural Resources Journal': 'Nat. Res. J.',
  'Nebraska Law Review': 'Neb. L. Rev.',
  'New Mexico Law Review': 'N.M. L. Rev.',
  'New York Law School Law Review': 'N.Y.L. Sch. L. Rev.',
  'North Dakota Law Review': 'N.D. L. Rev.',
  'Notre Dame Journal of Law, Ethics and Public Policy': 'Notre Dame J.L. Ethics & Pub. Pol\'y',
  'Oklahoma Law Review': 'Okla. L. Rev.',
  'Oregon Law Review': 'Or. L. Rev.',
  'Pepperdine Law Review': 'Pepp. L. Rev.',
  'Real Property, Trust and Estate Law Journal': 'Real Prop. Tr. & Est. L.J.',
  'Review of Litigation': 'Rev. Litig.',
  'Richmond Law Review': 'Rich. L. Rev.',
  'San Diego Law Review': 'San Diego L. Rev.',
  'Santa Clara Law Review': 'Santa Clara L. Rev.',
  'Seton Hall Law Review': 'Seton Hall L. Rev.',
  'South Carolina Law Review': 'S.C. L. Rev.',
  'South Dakota Law Review': 'S.D. L. Rev.',
  'South Texas Law Review': 'S. Tex. L. Rev.',
  'St. John\'s Law Review': 'St. John\'s L. Rev.',
  'St. Louis University Law Journal': 'St. Louis U. L.J.',
  'Suffolk University Law Review': 'Suffolk U. L. Rev.',
  'Supreme Court Review': 'Sup. Ct. Rev.',
  'Syracuse Law Review': 'Syracuse L. Rev.',
  'Tax Law Review': 'Tax L. Rev.',
  'Tennessee Law Review': 'Tenn. L. Rev.',
  'Texas International Law Journal': 'Tex. Int\'l L.J.',
  'Texas Tech Law Review': 'Tex. Tech L. Rev.',
  'Tort Trial and Insurance Practice Law Journal': 'Tort Trial & Ins. Prac. L.J.',
  'Tulsa Law Review': 'Tulsa L. Rev.',
  'University of Baltimore Law Review': 'U. Balt. L. Rev.',
  'University of Cincinnati Law Review': 'U. Cin. L. Rev.',
  'University of Colorado Law Review': 'U. Colo. L. Rev.',
  'University of Dayton Law Review': 'U. Dayton L. Rev.',
  'University of Detroit Mercy Law Review': 'U. Det. Mercy L. Rev.',
  'University of Florida Journal of Law and Public Policy': 'U. Fla. J.L. & Pub. Pol\'y',
  'University of Kansas Law Review': 'U. Kan. L. Rev.',
  'University of Memphis Law Review': 'U. Mem. L. Rev.',
  'University of Miami Law Review': 'U. Miami L. Rev.',
  'University of Michigan Journal of Law Reform': 'U. Mich. J.L. Reform',
  'University of Pittsburgh Law Review': 'U. Pitt. L. Rev.',
  'University of Richmond Law Review': 'U. Rich. L. Rev.',
  'University of San Francisco Law Review': 'U.S.F. L. Rev.',
  'University of Toledo Law Review': 'U. Tol. L. Rev.',
  'Utah Law Review': 'Utah L. Rev.',
  'Valparaiso University Law Review': 'Val. U. L. Rev.',
  'Vermont Law Review': 'Vt. L. Rev.',
  'Villanova Law Review': 'Vill. L. Rev.',
  'Virginia Journal of International Law': 'Va. J. Int\'l L.',
  'Virginia Tax Review': 'Va. Tax Rev.',
  'Washington and Lee Law Review': 'Wash. & Lee L. Rev.',
  'Wayne Law Review': 'Wayne L. Rev.',
  'West Virginia Law Review': 'W. Va. L. Rev.',
  'Widener Law Review': 'Widener L. Rev.',
  'Willamette Law Review': 'Willamette L. Rev.',
  'Yale Journal of International Law': 'Yale J. Int\'l L.',
  'Yale Journal on Regulation': 'Yale J. on Reg.',
  'Yale Law and Policy Review': 'Yale L. & Pol\'y Rev.',

  // ── International & Comparative Law Journals ────────────────────
  'American Journal of Comparative Law': 'Am. J. Comp. L.',
  'American Journal of International Law': 'Am. J. Int\'l L.',
  'British Yearbook of International Law': 'Brit. Y.B. Int\'l L.',
  'European Journal of International Law': 'Eur. J. Int\'l L.',
  'International and Comparative Law Quarterly': 'Int\'l & Comp. L.Q.',
  'International Law Review': 'Int\'l L. Rev.',
  'Leiden Journal of International Law': 'Leiden J. Int\'l L.',
  'Michigan Journal of International Law': 'Mich. J. Int\'l L.',
  'Vanderbilt Journal of Transnational Law': 'Vand. J. Transnat\'l L.',

  // ── Interdisciplinary Journals ──────────────────────────────────
  'American Bar Association Journal': 'A.B.A. J.',
  'American Journal of Law and Medicine': 'Am. J.L. & Med.',
  'Law and Philosophy': 'Law & Phil.',
  'Law and Society Review': 'Law & Soc\'y Rev.',
  'Stanford Technology Law Review': 'Stan. Tech. L. Rev.',
  'Yale Journal of Law and the Humanities': 'Yale J.L. & Human.',
  'Yale Journal of Law and Feminism': 'Yale J.L. & Feminism',
  'Yale Journal of Health Policy, Law, and Ethics': 'Yale J. Health Pol\'y L. & Ethics',

  // ── State Bar Journals & Regional ───────────────────────────────
  'Alabama Law Review': 'Ala. L. Rev.',
  'Alaska Law Review': 'Alaska L. Rev.',
  'Arizona Law Review': 'Ariz. L. Rev.',
  'Arkansas Law Review': 'Ark. L. Rev.',
  'Delaware Journal of Corporate Law': 'Del. J. Corp. L.',
  'Georgia State University Law Review': 'Ga. St. U. L. Rev.',
  'Hawaii Law Review': 'Haw. L. Rev.',
  'Idaho Law Review': 'Idaho L. Rev.',
  'Louisiana Law Review': 'La. L. Rev.',
  'Maine Law Review': 'Me. L. Rev.',
  'New Hampshire Bar Journal': 'N.H. B.J.',
  'New Jersey Law Journal': 'N.J. L.J.',
  'Pennsylvania Bar Association Quarterly': 'Pa. B. Ass\'n Q.',
  'Rhode Island Bar Journal': 'R.I. B.J.',
  'Wyoming Law Review': 'Wyo. L. Rev.',

  // ── Federal Practice & Procedure ────────────────────────────────
  'Federal Bar Journal': 'Fed. B.J.',
  'Federal Courts Law Review': 'Fed. Cts. L. Rev.',
  'Federal Sentencing Reporter': 'Fed. Sent\'g Rep.',

  // ── IP, Tech, and Cyberlaw ──────────────────────────────────────
  'Computer Law and Security Review': 'Comput. L. & Sec. Rev.',
  'Duke Law and Technology Review': 'Duke L. & Tech. Rev.',
  'Hastings Science and Technology Law Journal': 'Hastings Sci. & Tech. L.J.',
  'Houston Journal of International Law': 'Hous. J. Int\'l L.',
  'John Marshall Review of Intellectual Property Law': 'J. Marshall Rev. Intell. Prop. L.',
  'Santa Clara High Technology Law Journal': 'Santa Clara High Tech. L.J.',

  // ── Tax & Business ──────────────────────────────────────────────
  'Business Lawyer': 'Bus. Law.',
  'Uniform Commercial Code Law Journal': 'U.C.C. L.J.',
  'Virginia Law and Business Review': 'Va. L. & Bus. Rev.',
};

/** Reverse lookup: abbreviation → full name */
export const JOURNAL_ABBREVIATION_REVERSE: Record<string, string> = Object.fromEntries(
  Object.entries(JOURNAL_ABBREVIATIONS).map(([full, abbr]) => [abbr, full])
);
