import { v4 as uuid } from 'uuid';
import type { ParsedCitation, AiSourceComponents, CitationContext } from '@legalcitation/shared';

/**
 * Parse an AI-generated content citation (Rule 18.3, 22nd Edition).
 *
 * Formats:
 * - LLM: Author, Model (Version), "prompt" (Date) (on file with Repository).
 * - Search: Engine, "query", N results (Date) (on file with Repository).
 * - Generated: Description (on file with Repository) (generated by Model).
 */
export function parseAiSourceCitation(
  rawText: string,
  position: { start: number; end: number },
  context: CitationContext = 'citation_sentence'
): ParsedCitation | null {
  const text = rawText.trim().replace(/\.$/, '');

  const components = parseAiSource(text);
  if (!components) return null;

  return {
    id: uuid(),
    rawText: rawText.trim(),
    type: 'ai_source',
    context,
    position,
    components,
  };
}

const MODEL_NAMES = [
  'ChatGPT', 'GPT-4o', 'GPT-4', 'GPT-3.5',
  'Claude', 'Google Gemini Advanced', 'Google Gemini', 'Gemini Advanced',
  'Copilot', 'DALL-E 3', 'DALL-E', 'Midjourney', 'Stable Diffusion',
  'Perplexity', 'Llama', 'Mistral',
];

const SEARCH_ENGINES = ['Google', 'Bing', 'DuckDuckGo', 'Yahoo'];

function parseAiSource(text: string): AiSourceComponents | null {
  // Try generated content: "Description (on file with ...) (generated by Model)"
  const generatedPattern = /^(.+?)\s*\(on file with\s+(.+?)\)\s*\(generated by\s+(.+?)\)$/;
  let match = text.match(generatedPattern);
  if (match) {
    return {
      subtype: 'generated_content',
      modelName: match[3].trim(),
      contentDescription: match[1].trim(),
      onFileWith: match[2].trim(),
      date: '',
      generatedByModel: match[3].trim(),
    };
  }

  // Try search results: "Engine, "query", N results (Date) (on file with ...)"
  const searchPattern = /^([\w]+),\s*"([^"]+)",\s*([\d,]+\s+results)\s*\(([^)]+)\)\s*\(on file with\s+(.+?)\)$/;
  match = text.match(searchPattern);
  if (match && SEARCH_ENGINES.some(e => match![1].trim().includes(e))) {
    return {
      subtype: 'search',
      modelName: match[1].trim(),
      searchEngine: match[1].trim(),
      query: match[2].trim(),
      resultCount: match[3].trim(),
      date: match[4].trim(),
      onFileWith: match[5].trim(),
    };
  }

  // Try LLM citation: "Author, Model, "prompt" (Date) (on file with ...)"
  // Also: "Author, Model (Version), "prompt" (Date) (on file with ...)"
  for (const modelName of MODEL_NAMES) {
    const escapedModel = modelName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const llmPattern = new RegExp(
      `^(.+?),\\s*${escapedModel}(?:\\s*\\(([^)]+)\\))?,\\s*"([^"]+)"\\s*\\(([^)]+)\\)\\s*\\(on file with\\s+(.+?)\\)$`
    );
    match = text.match(llmPattern);
    if (match) {
      return {
        subtype: 'llm',
        promptAuthor: match[1].trim(),
        modelName,
        modelVersion: match[2]?.trim(),
        prompt: match[3].trim(),
        date: match[4].trim(),
        onFileWith: match[5].trim(),
      };
    }
  }

  // Fallback: detect model name anywhere with "(on file with"
  for (const modelName of MODEL_NAMES) {
    if (text.includes(modelName) && text.includes('(on file with')) {
      const onFileMatch = text.match(/\(on file with\s+(.+?)\)/);
      const dateMatch = text.match(/\(([A-Z][a-z]+\.?\s+\d{1,2},?\s+\d{4})\)/);
      return {
        subtype: 'llm',
        modelName,
        date: dateMatch ? dateMatch[1] : '',
        onFileWith: onFileMatch ? onFileMatch[1].trim() : undefined,
      };
    }
  }

  return null;
}
