import { v4 as uuid } from 'uuid';
import type { ValidationIssue, AiSourceComponents } from '@legalcitation/shared';

/**
 * Bluebook R. 18.3 — AI-Generated Content (22nd Edition).
 *
 * Three subtypes:
 *   (a) Large language models — prompt author, model (with version), exact prompt in quotes,
 *       date, on-file PDF. NO URL permitted.
 *   (b) Search results — search engine name (small caps), query in quotes, result count,
 *       date, on-file PDF. Filter parentheticals when content filters are used.
 *   (c) AI-generated content — cite per the relevant Bluebook subrule with an added
 *       "(generated by [Model])" parenthetical. Prompt author replaces "author" when available.
 */
export function validateAiSource(components: AiSourceComponents, rawText?: string): ValidationIssue[] {
  const issues: ValidationIssue[] = [];

  checkModelName(components, issues);
  checkDate(components, issues);
  checkOnFileWith(components, rawText, issues);

  switch (components.subtype) {
    case 'llm':
      checkLlmCitation(components, rawText, issues);
      break;
    case 'search':
      checkSearchCitation(components, rawText, issues);
      break;
    case 'generated_content':
      checkGeneratedContent(components, rawText, issues);
      break;
  }

  return issues;
}

function checkModelName(components: AiSourceComponents, issues: ValidationIssue[]): void {
  if (!components.modelName) {
    issues.push({
      id: uuid(),
      rule: 'R. 18.3',
      source: 'Bluebook',
      severity: 'error',
      message: 'AI citation must identify the AI tool or model used.',
      suggestion: 'Include the model name (e.g., "ChatGPT", "Claude", "Google Gemini Advanced").',
    });
    return;
  }

  // R. 18.3(a): "including version number if the model is identified according to version"
  const versionedModels = [
    { pattern: /^chatgpt$/i, suggestion: 'ChatGPT-4' },
    { pattern: /^gpt$/i, suggestion: 'GPT-4' },
    { pattern: /^claude$/i, suggestion: 'Claude 3.5 Sonnet' },
    { pattern: /^gemini$/i, suggestion: 'Google Gemini Advanced' },
    { pattern: /^copilot$/i, suggestion: 'CoPilot' },
  ];

  for (const { pattern, suggestion } of versionedModels) {
    if (pattern.test(components.modelName.trim()) && !components.modelVersion) {
      issues.push({
        id: uuid(),
        rule: 'R. 18.3(a)',
        source: 'Bluebook',
        severity: 'warning',
        message: `Model name "${components.modelName}" should include a version number when the model is identified by version.`,
        suggestion: `Specify the version (e.g., "${suggestion}").`,
      });
      break;
    }
  }
}

function checkDate(components: AiSourceComponents, issues: ValidationIssue[]): void {
  if (!components.date) {
    issues.push({
      id: uuid(),
      rule: 'R. 18.3',
      source: 'Bluebook',
      severity: 'error',
      message: 'AI citation must include the date of generation or search.',
      suggestion: 'Add the date in T.12 format (e.g., "(Mar. 29, 2024)").',
    });
  }
}

function checkOnFileWith(components: AiSourceComponents, rawText: string | undefined, issues: ValidationIssue[]): void {
  if (!components.onFileWith) {
    issues.push({
      id: uuid(),
      rule: 'R. 18.3',
      source: 'Bluebook',
      severity: 'error',
      message: 'AI citation must include "(on file with [repository])" because AI outputs are ephemeral and must be preserved as a PDF screenshot.',
      suggestion: 'Save a PDF screenshot of the output and add "(on file with the [journal name])".',
    });
    return;
  }

  // R. 18.3: The Bluebook requires "a screenshot capture of that output as a PDF to be stored on file"
  if (rawText && /\(on file with\b/i.test(rawText)) {
    // Validate the parenthetical is properly closed
    const onFileMatch = rawText.match(/\(on file with\s+([^)]*)\)/i);
    if (!onFileMatch) {
      issues.push({
        id: uuid(),
        rule: 'R. 18.3',
        source: 'Bluebook',
        severity: 'warning',
        message: '"(on file with ...)" parenthetical appears unclosed.',
        suggestion: 'Close the parenthetical: "(on file with the Columbia Law Review)".',
      });
    }
  }
}

function checkLlmCitation(components: AiSourceComponents, rawText: string | undefined, issues: ValidationIssue[]): void {
  // R. 18.3(a): Exact prompt text must be included in quotation marks
  if (!components.prompt) {
    issues.push({
      id: uuid(),
      rule: 'R. 18.3(a)',
      source: 'Bluebook',
      severity: 'error',
      message: 'LLM citation must include the exact text of the prompt submission in quotation marks.',
      suggestion: 'Add the prompt text in quotation marks (e.g., "Who would make a better Supreme Court Justice: Beyoncé or Taylor Swift?").',
    });
  } else if (rawText) {
    // Validate the prompt appears in quotes in the raw text
    const promptEscaped = components.prompt.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const quotedPromptPattern = new RegExp(`[""\u201c]${promptEscaped}[""\u201d]`);
    const hasQuotes = quotedPromptPattern.test(rawText)
      || rawText.includes(`"${components.prompt}"`)
      || rawText.includes(`\u201c${components.prompt}\u201d`);
    if (!hasQuotes) {
      issues.push({
        id: uuid(),
        rule: 'R. 18.3(a)',
        source: 'Bluebook',
        severity: 'warning',
        message: 'The prompt should appear in quotation marks in the citation.',
        suggestion: `Enclose the prompt in quotes: "${components.prompt}"`,
      });
    }
  }

  // R. 18.3(a): NO URL for LLM outputs — the "Not:" example in the rule text
  if (rawText && /https?:\/\//.test(rawText)) {
    issues.push({
      id: uuid(),
      rule: 'R. 18.3(a)',
      source: 'Bluebook',
      severity: 'error',
      message: 'LLM citations must not include a URL. AI chat outputs are individualized and ephemeral; a URL will not suffice. Use "(on file with ...)" instead.',
      suggestion: 'Remove the URL and ensure a PDF screenshot is saved on file.',
    });
  }

  // R. 18.3(a): Prompt author should be identified
  if (!components.promptAuthor) {
    issues.push({
      id: uuid(),
      rule: 'R. 18.3(a)',
      source: 'Bluebook',
      severity: 'warning',
      message: 'LLM citation should identify the author of the prompt.',
      suggestion: 'Add the prompt author before the model name (e.g., "Luke Cronin, Google Gemini Advanced, ...").',
    });
  }
}

function checkSearchCitation(components: AiSourceComponents, rawText: string | undefined, issues: ValidationIssue[]): void {
  // R. 18.3(b): Search engine name required (in small caps)
  if (!components.searchEngine) {
    issues.push({
      id: uuid(),
      rule: 'R. 18.3(b)',
      source: 'Bluebook',
      severity: 'error',
      message: 'Search result citation must identify the search engine in small caps.',
      suggestion: 'Include the search engine name (e.g., "Bing", "Westlaw", "Google").',
    });
  }

  // R. 18.3(b): Query must be in quotation marks
  if (!components.query) {
    issues.push({
      id: uuid(),
      rule: 'R. 18.3(b)',
      source: 'Bluebook',
      severity: 'error',
      message: 'Search result citation must include the exact search query in quotation marks.',
      suggestion: 'Add the search query in quotes (e.g., "The Bluebook").',
    });
  } else if (rawText) {
    // R. 18.3(b): "commas that were not part of the search query should be kept outside quotation marks"
    const queryInText = rawText.includes(`"${components.query}"`);
    if (!queryInText) {
      // Check for query with trailing comma inside quotes
      if (rawText.includes(`"${components.query},"`)) {
        issues.push({
          id: uuid(),
          rule: 'R. 18.3(b)',
          source: 'Bluebook',
          severity: 'warning',
          message: 'Commas that are not part of the search query should be kept outside the quotation marks.',
          suggestion: `Use "${components.query}", not "${components.query},"`,
        });
      }
    }
  }

  // R. 18.3(b): Result count
  if (!components.resultCount) {
    issues.push({
      id: uuid(),
      rule: 'R. 18.3(b)',
      source: 'Bluebook',
      severity: 'warning',
      message: 'Search result citation should include the number of results.',
      suggestion: 'Add the result count (e.g., "6,050,000 results").',
    });
  }

  // R. 18.3(b): Check for filter parenthetical when content filters are employed
  if (rawText && /\bfilter/i.test(rawText) && !/\(filtered by\b/i.test(rawText)) {
    issues.push({
      id: uuid(),
      rule: 'R. 18.3(b)',
      source: 'Bluebook',
      severity: 'suggestion',
      message: 'When content filters narrow search results, indicate the filters in a parenthetical.',
      suggestion: 'Add a filter parenthetical (e.g., "(filtered by \u201cCases\u201d, \u201c2d Cir.\u201d)").',
    });
  }
}

function checkGeneratedContent(components: AiSourceComponents, rawText: string | undefined, issues: ValidationIssue[]): void {
  // R. 18.3(c): Must include "(generated by [Model])" parenthetical
  if (!components.generatedByModel) {
    issues.push({
      id: uuid(),
      rule: 'R. 18.3(c)',
      source: 'Bluebook',
      severity: 'error',
      message: 'AI-generated content citation must include a "(generated by [Model])" parenthetical indicating the AI model used.',
      suggestion: 'Add a parenthetical (e.g., "(generated by DALL-E 3)" or "(generated by Midjourney AI)").',
    });
  }

  // R. 18.3(c): Validate parenthetical format in raw text
  if (rawText && components.generatedByModel) {
    const generatedByPattern = /\(generated by\s+[^)]+\)/i;
    if (!generatedByPattern.test(rawText)) {
      issues.push({
        id: uuid(),
        rule: 'R. 18.3(c)',
        source: 'Bluebook',
        severity: 'warning',
        message: 'The "(generated by [Model])" parenthetical should follow the standard format.',
        suggestion: `Use "(generated by ${components.generatedByModel})".`,
      });
    }
  }

  // R. 18.3(c): Content description or title is expected
  if (!components.contentDescription) {
    issues.push({
      id: uuid(),
      rule: 'R. 18.3(c)',
      source: 'Bluebook',
      severity: 'suggestion',
      message: 'AI-generated content should include a description or title per the relevant Bluebook subrule for the content type.',
      suggestion: 'Add a descriptive title (e.g., "Illustration of a Tornado on the Moon").',
    });
  }
}
