import { v4 as uuid } from 'uuid';
import type { ValidationIssue, AiSourceComponents } from '@legalcitation/shared';

/**
 * Bluebook R. 18.3 — AI-Generated Content (22nd Edition).
 * Validates citations to AI-generated outputs, search results, and AI-created content.
 */
export function validateAiSource(components: AiSourceComponents, rawText?: string): ValidationIssue[] {
  const issues: ValidationIssue[] = [];

  checkModelName(components, issues);
  checkDate(components, issues);
  checkOnFileWith(components, issues);

  switch (components.subtype) {
    case 'llm':
      checkLlmCitation(components, rawText, issues);
      break;
    case 'search':
      checkSearchCitation(components, issues);
      break;
    case 'generated_content':
      checkGeneratedContent(components, issues);
      break;
  }

  return issues;
}

function checkModelName(components: AiSourceComponents, issues: ValidationIssue[]): void {
  if (!components.modelName) {
    issues.push({
      id: uuid(),
      rule: 'R. 18.3',
      source: 'Bluebook',
      severity: 'error',
      message: 'AI citation must identify the AI tool or model used.',
      suggestion: 'Include the model name (e.g., "ChatGPT", "Claude", "Google Gemini Advanced").',
    });
  }
}

function checkDate(components: AiSourceComponents, issues: ValidationIssue[]): void {
  if (!components.date) {
    issues.push({
      id: uuid(),
      rule: 'R. 18.3',
      source: 'Bluebook',
      severity: 'error',
      message: 'AI citation must include the date of generation.',
      suggestion: 'Add the date the AI output was generated (e.g., "(Mar. 29, 2024)").',
    });
  }
}

function checkOnFileWith(components: AiSourceComponents, issues: ValidationIssue[]): void {
  if (!components.onFileWith) {
    issues.push({
      id: uuid(),
      rule: 'R. 18.3',
      source: 'Bluebook',
      severity: 'error',
      message: 'AI citation must include "(on file with [repository])" because AI outputs are not permanently accessible.',
      suggestion: 'Add "(on file with the [journal name])" to indicate where the output is preserved.',
    });
  }
}

function checkLlmCitation(components: AiSourceComponents, rawText: string | undefined, issues: ValidationIssue[]): void {
  // R. 18.3(a): Prompt must be included in quotation marks
  if (!components.prompt) {
    issues.push({
      id: uuid(),
      rule: 'R. 18.3(a)',
      source: 'Bluebook',
      severity: 'error',
      message: 'LLM citation must include the exact prompt in quotation marks.',
      suggestion: 'Add the prompt text in quotation marks (e.g., "What is the meaning of life?").',
    });
  }

  // R. 18.3(a): NO URL for LLM outputs
  if (rawText && /https?:\/\//.test(rawText)) {
    issues.push({
      id: uuid(),
      rule: 'R. 18.3(a)',
      source: 'Bluebook',
      severity: 'error',
      message: 'LLM citations should not include a URL. AI chat outputs are ephemeral and not permanently available at a URL.',
      suggestion: 'Remove the URL and use "(on file with [repository])" instead.',
    });
  }

  // Prompt author should be identified
  if (!components.promptAuthor) {
    issues.push({
      id: uuid(),
      rule: 'R. 18.3(a)',
      source: 'Bluebook',
      severity: 'warning',
      message: 'LLM citation should identify the person who prompted the AI.',
      suggestion: 'Add the prompt author before the model name.',
    });
  }
}

function checkSearchCitation(components: AiSourceComponents, issues: ValidationIssue[]): void {
  if (!components.searchEngine) {
    issues.push({
      id: uuid(),
      rule: 'R. 18.3(b)',
      source: 'Bluebook',
      severity: 'error',
      message: 'Search result citation must identify the search engine.',
      suggestion: 'Include the search engine name (e.g., "Google", "Bing").',
    });
  }

  if (!components.query) {
    issues.push({
      id: uuid(),
      rule: 'R. 18.3(b)',
      source: 'Bluebook',
      severity: 'error',
      message: 'Search result citation must include the search query in quotation marks.',
      suggestion: 'Add the search query in quotes (e.g., "The Bluebook").',
    });
  }

  if (!components.resultCount) {
    issues.push({
      id: uuid(),
      rule: 'R. 18.3(b)',
      source: 'Bluebook',
      severity: 'warning',
      message: 'Search result citation should include the number of results.',
      suggestion: 'Add the result count (e.g., "6,050,000 results").',
    });
  }
}

function checkGeneratedContent(components: AiSourceComponents, issues: ValidationIssue[]): void {
  if (!components.generatedByModel) {
    issues.push({
      id: uuid(),
      rule: 'R. 18.3(c)',
      source: 'Bluebook',
      severity: 'error',
      message: 'AI-generated content citation must include "(generated by [Model])" parenthetical.',
      suggestion: 'Add "(generated by DALL-E 3)" or similar parenthetical.',
    });
  }
}
